package com.lazybu0y.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "RepoScanResult")

public class RepoScanResult {
    private String scanId;
    private String repoName;
    private FileScanResult fileScanResult;

    @DynamoDBHashKey(attributeName = "ScanId")
    @DynamoDBAutoGeneratedKey
    public String getScanId() {
        return scanId;
    }

    public void setScanId(String scanId) {
        this.scanId = scanId;
    }

    @DynamoDBRangeKey(attributeName = "RepoName")
    public String getRepoName() {
        return repoName;
    }

    public void setRepoName(String repoName) {
        this.repoName = repoName;
    }

    public FileScanResult getFileScanResult() {
        return fileScanResult;
    }
    @DynamoDBAttribute(attributeName = "FileScanResult")
    public void setFileScanResult(FileScanResult fileScanResult) {
        this.fileScanResult = fileScanResult;
    }
}
